import { customProvider } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import type { ChatMode, SelectedModel } from "@/types/chat";
import { isAgentMode } from "@/lib/utils/mode-helpers";
import { openrouterAttributionHeaders } from "@/lib/ai/openrouter-attribution";
// import { withTracing } from "@posthog/ai";
// import PostHogClient from "@/app/posthog";
// import type { SubscriptionTier } from "@/types";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

const isXaiModelSlug = (value: unknown): boolean =>
  typeof value === "string" && value.toLowerCase().startsWith("x-ai/");

const requestCanRouteToXai = (body: unknown): boolean => {
  if (!isRecord(body)) return false;
  if (isXaiModelSlug(body.model)) return true;
  return Array.isArray(body.models) && body.models.some(isXaiModelSlug);
};

const hasOwnEncryptedContent = (value: unknown): boolean =>
  isRecord(value) && Object.hasOwn(value, "encrypted_content");

const stripEncryptedContent = (
  value: unknown,
  inReasoningDetails = false,
): { value: unknown; changed: boolean } => {
  if (Array.isArray(value)) {
    let changed = false;
    const cleaned: unknown[] = [];

    for (const item of value) {
      if (inReasoningDetails && hasOwnEncryptedContent(item)) {
        changed = true;
        continue;
      }
      const result = stripEncryptedContent(item, inReasoningDetails);
      changed ||= result.changed;
      cleaned.push(result.value);
    }

    return changed ? { value: cleaned, changed } : { value, changed: false };
  }

  if (!isRecord(value)) {
    return { value, changed: false };
  }

  let changed = false;
  const cleaned: Record<string, unknown> = {};

  for (const [key, entryValue] of Object.entries(value)) {
    if (inReasoningDetails && key === "encrypted_content") {
      changed = true;
      continue;
    }

    const nextInReasoningDetails =
      inReasoningDetails || key === "reasoning_details";
    const result = stripEncryptedContent(entryValue, nextInReasoningDetails);
    changed ||= result.changed;

    if (
      key === "reasoning_details" &&
      Array.isArray(result.value) &&
      result.value.length === 0
    ) {
      changed = true;
      continue;
    }

    cleaned[key] = result.value;
  }

  return changed ? { value: cleaned, changed } : { value, changed: false };
};

export const sanitizeOpenRouterRequestForXai = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (
    !isRecord(body) ||
    !requestCanRouteToXai(body) ||
    !Array.isArray(body.messages)
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    const result = stripEncryptedContent(message);
    changed ||= result.changed;
    return result.value;
  });

  if (!changed) return { body, changed: false };
  return { body: { ...body, messages }, changed: true };
};

const patchKimiReasoningToolCalls = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (!isRecord(body)) return { body, changed: false };
  if (
    !Array.isArray(body.messages) ||
    !isRecord(body.reasoning) ||
    body.reasoning.enabled !== true
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    if (
      isRecord(message) &&
      message.role === "assistant" &&
      Array.isArray(message.tool_calls) &&
      message.tool_calls.length > 0 &&
      !message.reasoning
    ) {
      changed = true;
      return { ...message, reasoning: "." };
    }
    return message;
  });

  return changed
    ? { body: { ...body, messages }, changed: true }
    : { body, changed: false };
};

const OPENROUTER_METADATA_HEADER = "X-OpenRouter-Experimental-Metadata";

const withOpenRouterMetadataHeader = (
  headers: HeadersInit | undefined,
): Headers => {
  const nextHeaders = new Headers(headers);
  if (!nextHeaders.has(OPENROUTER_METADATA_HEADER)) {
    nextHeaders.set(OPENROUTER_METADATA_HEADER, "enabled");
  }
  return nextHeaders;
};

// Custom fetch for OpenRouter provider-specific request-body repairs.
//
// - Kimi requires a `reasoning` field on assistant tool-call messages when
//   reasoning mode is enabled, but the AI SDK does not always include one.
// - xAI rejects encrypted reasoning blobs generated by a different provider
//   when OpenRouter falls back to Grok. The visible assistant text remains in
//   the prompt, so these provider-private blobs are safe to omit for xAI routes.
// - The metadata header opts into OpenRouter routing metadata for attribution.
const openrouterPatchFetch: typeof fetch = async (url, init) => {
  let nextInit: RequestInit = {
    ...init,
    headers: withOpenRouterMetadataHeader(init?.headers),
  };

  if (nextInit.body && typeof nextInit.body === "string") {
    try {
      const parsedBody = JSON.parse(nextInit.body) as unknown;
      const kimiPatched = patchKimiReasoningToolCalls(parsedBody);
      const xaiPatched = sanitizeOpenRouterRequestForXai(kimiPatched.body);
      if (kimiPatched.changed || xaiPatched.changed) {
        nextInit = { ...nextInit, body: JSON.stringify(xaiPatched.body) };
      }
    } catch {
      // If parsing fails, send the request as-is
    }
  }
  return globalThis.fetch(url, nextInit);
};

const openrouter = createOpenRouter({
  fetch: openrouterPatchFetch,
  headers: openrouterAttributionHeaders,
});

type OpenRouterInstance = typeof openrouter;

const buildProviderMap = (or: OpenRouterInstance) =>
  ({
    "ask-model": or("google/gemini-3-flash-preview"),
    // Free tiers route to Grok 4.3 (xAI). DeepSeek/Kimi are Chinese models whose
    // built-in safety layer hard-refuses OSINT / offensive-security work with an
    // un-overridable "你好，我无法给到相关内容。" — the system prompt cannot stop it.
    // Grok 4.3 has no such cyber content-filter and actually serves the output.
    "ask-model-free": or("x-ai/grok-4.3"),
    // Paid auto agent path — Grok too (was Kimi K2.7-code, a Chinese model that
    // refused OSINT). Every agent route now lands on the non-refusing Grok 4.3.
    "agent-model": or("x-ai/grok-4.3"),
    "agent-model-free": or("x-ai/grok-4.3"),
    "model-sonnet-4.6": or("anthropic/claude-sonnet-4.6"),
    "model-gemini-3-flash": or("google/gemini-3-flash-preview"),
    "model-deepseek-v4-flash": or("deepseek/deepseek-v4-flash"),
    "model-opus-4.6": or("anthropic/claude-opus-4.6"),
    "model-opus-4.8": or("anthropic/claude-opus-4.8"),
    "model-kimi-k2.6": or("moonshotai/kimi-k2.6:exacto"),
    // Permissive, frontier-tier models that do NOT apply a cyber content-filter
    // (unlike Claude/GPT/Gemini), so they actually serve offensive-security
    // output. Grok 4.3 = the best practical pentest model; Kimi K2.7-code = top
    // agentic-coding workhorse.
    "model-grok-4.3": or("x-ai/grok-4.3"),
    "model-kimi-k2.7-code": or("moonshotai/kimi-k2.7-code"),
    "fallback-agent-model": or("google/gemini-3-flash-preview"),
    "fallback-ask-model": or("google/gemini-3-flash-preview"),
    "fallback-gemini-3.5-flash": or("google/gemini-3.5-flash"),
    "fallback-grok-4.3": or("x-ai/grok-4.3"),
    "title-generator-model": or("google/gemini-2.5-flash"),
  }) as Record<string, any>;

const baseProviders = buildProviderMap(openrouter);

export type ModelName = keyof typeof baseProviders;

export const modelCutoffDates: Record<ModelName, string> &
  Record<string, string> = {
  "ask-model": "January 2025",
  "ask-model-free": "Late 2025",
  "agent-model": "Late 2025",
  "agent-model-free": "Late 2025",
  "model-sonnet-4.6": "May 2025",
  "model-gemini-3-flash": "January 2025",
  "model-deepseek-v4-flash": "May 2025",
  "model-opus-4.6": "May 2025",
  "model-opus-4.8": "Early 2026",
  "model-kimi-k2.6": "April 2024",
  "model-grok-4.3": "Late 2025",
  "model-kimi-k2.7-code": "April 2024",
  "fallback-agent-model": "January 2025",
  "fallback-ask-model": "January 2025",
  "fallback-gemini-3.5-flash": "May 2026",
  "fallback-grok-4.3": "December 2025",
  "title-generator-model": "January 2025",
};

export const modelDisplayNames: Record<ModelName, string> &
  Record<string, string> = {
  "ask-model": "Auto, an intelligent model router built by RIFT",
  "ask-model-free": "Auto, an intelligent model router built by RIFT",
  "agent-model": "Auto, an intelligent model router built by RIFT",
  "agent-model-free": "Auto, an intelligent model router built by RIFT",
  "model-sonnet-4.6": "Anthropic Claude Sonnet 4.6",
  "model-gemini-3-flash": "Google Gemini 3 Flash",
  "model-deepseek-v4-flash": "DeepSeek V4 Flash",
  "model-opus-4.6": "Anthropic Claude Opus 4.6",
  "model-opus-4.8": "Anthropic Claude Opus 4.8",
  "model-kimi-k2.6": "Moonshot Kimi K2.6",
  "model-grok-4.3": "xAI Grok 4.3",
  "model-kimi-k2.7-code": "Moonshot Kimi K2.7 Code",
  "fallback-agent-model": "Auto, an intelligent model router built by RIFT",
  "fallback-ask-model": "Auto, an intelligent model router built by RIFT",
  "fallback-gemini-3.5-flash": "Google Gemini 3.5 Flash",
  "fallback-grok-4.3": "Auto, an intelligent model router built by RIFT",
  "title-generator-model": "Google Gemini 2.5 Flash",
};

export const getModelDisplayName = (modelName: ModelName): string => {
  return modelDisplayNames[modelName];
};

export const getModelCutoffDate = (modelName: ModelName): string => {
  return modelCutoffDates[modelName];
};

export function isAnthropicModel(modelName: string): boolean {
  return modelName.includes("sonnet") || modelName.includes("opus");
}

export function isDeepSeekModel(modelName: string): boolean {
  // NOTE: ask-model-free / agent-model-free now route to Grok 4.3, not DeepSeek.
  // Only the explicit DeepSeek key remains.
  return modelName === "model-deepseek-v4-flash";
}

export function supportsMultimodalToolResults(modelName?: string): boolean {
  if (!modelName) return false;

  const normalized = modelName.toLowerCase();

  return (
    normalized === "ask-model" ||
    // Free tiers are Grok 4.3-backed (vision-capable) — see buildProviderMap.
    normalized === "ask-model-free" ||
    normalized === "agent-model-free" ||
    normalized.includes("gemini") ||
    normalized.includes("google/") ||
    isAnthropicModel(normalized) ||
    normalized.includes("anthropic/") ||
    normalized.includes("claude") ||
    normalized.includes("openai/") ||
    normalized.includes("gpt-") ||
    normalized.includes("o1") ||
    normalized.includes("o3") ||
    normalized.includes("o4") ||
    normalized.includes("x-ai/") ||
    normalized.includes("grok")
  );
}

export function isGeminiModel(modelName: string): boolean {
  return modelName === "ask-model" || modelName === "model-gemini-3-flash";
}

/**
 * Map a RIFT tier id to the underlying provider key for a given mode.
 * Returns `null` for `"auto"` (the caller routes to the auto-router model
 * key instead).
 *
 * AGENT mode = live pentest/OSINT → ALL tiers use Grok 4.3. The Chinese models
 * (Kimi K2.6 / K2.7-code, DeepSeek) have a built-in safety layer that hard-
 * refuses OSINT/offensive-security work — empirically they reply "你好，我无法
 * 给到相关内容。" (or, when told not to use Chinese, a generic refusal in another
 * language) and the system prompt cannot override it. Grok 4.3 (xAI) has no such
 * cyber content-filter and reliably serves the output, so every agent tier routes
 * to it. Ask mode (conversational) keeps the cheaper Gemini for Recon.
 */
export function resolveTierToProviderKey(
  tier: SelectedModel,
  mode: ChatMode,
): ModelName | null {
  if (tier === "auto") return null;
  switch (tier) {
    case "rift-standard":
      // Recon: agent → Grok (no refusal); ask → Gemini 3 Flash (cheap, fine).
      return isAgentMode(mode) ? "model-grok-4.3" : "model-gemini-3-flash";
    case "rift-pro":
      // Strike → Grok 4.3 (was Kimi K2.7-code, which refused OSINT in Chinese).
      return "model-grok-4.3";
    case "rift-max":
      // Dominate → Grok 4.3: the best PRACTICAL pentest model. Frontier-tier
      // cyber capability AND permissive — it actually serves offensive-security
      // output, unlike Claude/Opus (real-time content-filter) or the Chinese
      // models (Chinese safety refusal).
      return "model-grok-4.3";
  }
}

export const myProvider = customProvider({
  languageModels: baseProviders,
});

export const createTrackedProvider = () =>
  // userId?: string,
  // conversationId?: string,
  // subscription?: SubscriptionTier,
  // phClient?: ReturnType<typeof PostHogClient> | null,
  {
    // PostHog provider tracking disabled
    // if (!phClient || subscription === "free") {
    //   return myProvider;
    // }
    //
    // const trackedModels: Record<string, any> = {};
    //
    // Object.entries(baseProviders).forEach(([modelName, model]) => {
    //   trackedModels[modelName] = withTracing(model, phClient, {
    //     ...(userId && { posthogDistinctId: userId }),
    //     posthogProperties: {
    //       modelType: modelName,
    //       ...(conversationId && { conversationId }),
    //       subscriptionTier: subscription,
    //     },
    //     posthogPrivacyMode: true,
    //   });
    // });
    //
    // return customProvider({
    //   languageModels: trackedModels,
    // });

    return myProvider;
  };
